salida: ListNode.o LinkedList.o main.o
	g++ LinkedList.o ListNode.o main.o -o output
main.o:
	g++ -c main.cpp
ListNode.o:
	g++ -c ListNode.cpp
LinkedList.o:
	g++ -c LinkedList.cpp
clean:
	rm *.o
com:
	./output
